name: Tafakor Video
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  render:
    name: Render Video
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - uses: actions/setup-node@v3

      # Setup Bun (JavaScript runtime)
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install system dependencies
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
            libxrandr2 libgbm1 dbus-x11 dbus libdbus-1-dev libdbus-glib-1-dev && sudo apt -y install systemd && sudo apt-get remove -y google-chrome-stable && sudo apt-get install google-chrome-stable -y && dbus-launch
      # sudo service dbus start

      - name: Disable Dbus
        run: DBUS_SESSION_BUS_ADDRESS="autolaunch:"


      # Setup Chrome for rendering
      # - uses: browser-actions/setup-chrome@v1

      # - name: Configure Chrome
      #   run: |
      #     which chrome && PATH="$PATH:$(which chrome)"
      #     alias google-chrome='chrome'
      #     sudo cp $(which chrome) /usr/bin/g-chrome

      # Install project dependencies
      - name: Install Dependencies
        run: bun install

      # Set environment variables
      - name: Set Environment Variables
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env

      # Render the video
      - name: Render Video
        run: npm run pipe

      # Upload the rendered video as an artifact
      - name: Upload Rendered Video
        uses: actions/upload-artifact@v3
        with:
          name: rendered-video
          path: out/*.mp4
